### PR TITLE
Custom Mincer processors

### PR DESCRIPTION
**Pull request by winniehell**
@steel Could you please take a look? :smiley: 

This is not tested yet, I plan to do that tomorrow.

### CODE REVIEW

**Comment by winniehell** [comment]
@steel I made a test project: https://github.com/winniehell-forks/karma-sprockets-mincer/tree/test-processors/

After a few bug fixes this seems to work. :smile:

**Comment by steel** [comment]
@winniehell I apologize that this slipped through the cracks. Are you still advocating for this feature?

**Comment by winniehell** [comment]
@steel We switched from mincer to Webpack but I wouldn't mind finishing this merge request. :wink:

**Comment by winniehell** [comment]
I guess after waiting for 6 years, I can safely assume that this will not be merged. I'll close it now.

**Pull request closed without merging**
