### PR TITLE
Dependencies update for 0.12.0 node

### PR DESCRIPTION
**Pull request by Coobaha**
@steel dont forget to bump version if You will merge this :yum:

### CODE REVIEW

**Comment by Coobaha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by Coobaha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by steel** [comment]
Thanks for the pull request!

**Comment by steel** [comment]
bumped version as well.

**Comment by Coobaha** [comment]
:+1:

**Pull request merged**
